# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quanLyDiemDanh1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1682, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 1621, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.btn_page_dangky = QtWidgets.QPushButton(self.groupBox)
        self.btn_page_dangky.setGeometry(QtCore.QRect(150, 20, 211, 51))
        self.btn_page_dangky.setStyleSheet("\n"
"#btn_page_dangky {\n"
"    background-color: #4d4dff; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 1px solid #ff6666; /* Viền */\n"
"    border-radius: 4px; /* Viền tròn */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 20px; /* Cỡ chữ */\n"
"    cursor: pointer; /* Con trỏ chuột khi hover */\n"
"    transition: background-color 0.3s, color 0.3s; /* Hiệu ứng chuyển đổi màu nền và màu chữ */\n"
"}\n"
"\n"
"#btn_page_dangky:hover {\n"
"    background-color: #6666ff; /* Màu nền khi hover */\n"
"    color: #fff; /* Màu chữ khi hover */\n"
"}\n"
"")
        self.btn_page_dangky.setObjectName("btn_page_dangky")
        self.btn_page_quanly = QtWidgets.QPushButton(self.groupBox)
        self.btn_page_quanly.setGeometry(QtCore.QRect(400, 20, 221, 51))
        self.btn_page_quanly.setStyleSheet("\n"
"#btn_page_quanly {\n"
"    background-color: #4d4dff; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 1px solid #ff6666; /* Viền */\n"
"    border-radius: 4px; /* Viền tròn */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 20px; /* Cỡ chữ */\n"
"    cursor: pointer; /* Con trỏ chuột khi hover */\n"
"    transition: background-color 0.3s, color 0.3s; /* Hiệu ứng chuyển đổi màu nền và màu chữ */\n"
"}\n"
"\n"
"#btn_page_quanly:hover {\n"
"    background-color: #6666ff; /* Màu nền khi hover */\n"
"    color: #fff; /* Màu chữ khi hover */\n"
"}\n"
"")
        self.btn_page_quanly.setObjectName("btn_page_quanly")
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_frameBarCode = QtWidgets.QLabel(self.groupBox_3)
        self.label_frameBarCode.setGeometry(QtCore.QRect(10, 30, 461, 311))
        self.label_frameBarCode.setFrameShape(QtWidgets.QFrame.Box)
        self.label_frameBarCode.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_frameBarCode.setLineWidth(5)
        self.label_frameBarCode.setScaledContents(True)
        self.label_frameBarCode.setObjectName("label_frameBarCode")
        self.btn_openCam = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_openCam.setGeometry(QtCore.QRect(480, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_openCam.setFont(font)
        self.btn_openCam.setStyleSheet("#btn_openCam {\n"
"    background-color: #1a75ff; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 1px solid #ff6666; /* Viền */\n"
"    border-radius: 4px; /* Viền tròn */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 20px; /* Cỡ chữ */\n"
"    cursor: pointer; /* Con trỏ chuột khi hover */\n"
"    transition: background-color 0.3s, color 0.3s; /* Hiệu ứng chuyển đổi màu nền và màu chữ */\n"
"}\n"
"\n"
"#btn_openCam:hover {\n"
"    background-color: #4d94ff; /* Màu nền khi hover */\n"
"    color: #fff; /* Màu chữ khi hover */\n"
"}\n"
"")
        self.btn_openCam.setObjectName("btn_openCam")
        self.btn_closeCam = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_closeCam.setGeometry(QtCore.QRect(640, 30, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_closeCam.setFont(font)
        self.btn_closeCam.setStyleSheet("#btn_closeCam {\n"
"    background-color: #ff6666; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 1px solid #ff6666; /* Viền */\n"
"    border-radius: 4px; /* Viền tròn */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 18px; /* Cỡ chữ */\n"
"    cursor: pointer; /* Con trỏ chuột khi hover */\n"
"    transition: background-color 0.3s, color 0.3s; /* Hiệu ứng chuyển đổi màu nền và màu chữ */\n"
"}\n"
"\n"
"#btn_closeCam:hover {\n"
"    background-color: #ff4d4d; /* Màu nền khi hover */\n"
"    color: #fff; /* Màu chữ khi hover */\n"
"}\n"
"")
        self.btn_closeCam.setObjectName("btn_closeCam")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 500, 761, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 391, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.formLayoutWidget.setFont(font)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.input_ma_mon = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_ma_mon.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_ma_mon.setFont(font)
        self.input_ma_mon.setObjectName("input_ma_mon")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_ma_mon)
        self.emailLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.input_nhom = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_nhom.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_nhom.setFont(font)
        self.input_nhom.setObjectName("input_nhom")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_nhom)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.input_tuan_hoc = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_tuan_hoc.setMaximumSize(QtCore.QSize(260, 16777215))
        self.input_tuan_hoc.setObjectName("input_tuan_hoc")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_tuan_hoc)
        self.btn_tim_danhSach = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_tim_danhSach.setGeometry(QtCore.QRect(410, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_tim_danhSach.setFont(font)
        self.btn_tim_danhSach.setStyleSheet("#btn_tim_danhSach {\n"
"    background-color: #1a75ff; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 1px solid #ff6666; /* Viền */\n"
"    border-radius: 4px; /* Viền tròn */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 20px; /* Cỡ chữ */\n"
"    cursor: pointer; /* Con trỏ chuột khi hover */\n"
"    transition: background-color 0.3s, color 0.3s; /* Hiệu ứng chuyển đổi màu nền và màu chữ */\n"
"}\n"
"\n"
"#btn_tim_danhSach:hover {\n"
"    background-color: #4d94ff; /* Màu nền khi hover */\n"
"    color: #fff; /* Màu chữ khi hover */\n"
"}\n"
"")
        self.btn_tim_danhSach.setObjectName("btn_tim_danhSach")
        self.btn_luu_danh_sach = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_luu_danh_sach.setGeometry(QtCore.QRect(410, 90, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_luu_danh_sach.setFont(font)
        self.btn_luu_danh_sach.setStyleSheet("#btn_luu_danh_sach {\n"
"    background-color: #1a75ff; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 1px solid #ff6666; /* Viền */\n"
"    border-radius: 4px; /* Viền tròn */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 20px; /* Cỡ chữ */\n"
"    cursor: pointer; /* Con trỏ chuột khi hover */\n"
"    transition: background-color 0.3s, color 0.3s; /* Hiệu ứng chuyển đổi màu nền và màu chữ */\n"
"}\n"
"\n"
"#btn_luu_danh_sach:hover {\n"
"    background-color: #4d94ff; /* Màu nền khi hover */\n"
"    color: #fff; /* Màu chữ khi hover */\n"
"}\n"
"")
        self.btn_luu_danh_sach.setObjectName("btn_luu_danh_sach")
        self.btn_export_file = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_export_file.setGeometry(QtCore.QRect(600, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_export_file.setFont(font)
        self.btn_export_file.setStyleSheet("#btn_export_file {\n"
"    background-color: #00b300; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 1px solid #ff6666; /* Viền */\n"
"    border-radius: 4px; /* Viền tròn */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 18px; /* Cỡ chữ */\n"
"    cursor: pointer; /* Con trỏ chuột khi hover */\n"
"    transition: background-color 0.3s, color 0.3s; /* Hiệu ứng chuyển đổi màu nền và màu chữ */\n"
"}\n"
"\n"
"#btn_export_file:hover {\n"
"    background-color: #00cc00; /* Màu nền khi hover */\n"
"    color: #fff; /* Màu chữ khi hover */\n"
"}\n"
"")
        self.btn_export_file.setObjectName("btn_export_file")
        self.btn_clear_input = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_clear_input.setGeometry(QtCore.QRect(600, 90, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_clear_input.setFont(font)
        self.btn_clear_input.setStyleSheet("#btn_clear_input {\n"
"    background-color: #ff6666; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 1px solid #ff6666; /* Viền */\n"
"    border-radius: 4px; /* Viền tròn */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 20px; /* Cỡ chữ */\n"
"    cursor: pointer; /* Con trỏ chuột khi hover */\n"
"    transition: background-color 0.3s, color 0.3s; /* Hiệu ứng chuyển đổi màu nền và màu chữ */\n"
"}\n"
"\n"
"#btn_clear_input:hover {\n"
"    background-color: #ff4d4d; /* Màu nền khi hover */\n"
"    color: #fff; /* Màu chữ khi hover */\n"
"}\n"
"")
        self.btn_clear_input.setObjectName("btn_clear_input")
        self.label_sinh_vien = QtWidgets.QLabel(self.groupBox_3)
        self.label_sinh_vien.setGeometry(QtCore.QRect(500, 90, 231, 251))
        self.label_sinh_vien.setFrameShape(QtWidgets.QFrame.Box)
        self.label_sinh_vien.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_sinh_vien.setLineWidth(2)
        self.label_sinh_vien.setText("")
        self.label_sinh_vien.setPixmap(QtGui.QPixmap("img/pic_user.png"))
        self.label_sinh_vien.setScaledContents(True)
        self.label_sinh_vien.setObjectName("label_sinh_vien")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 350, 761, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 351, 91))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.hTNLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.hTNLabel.setObjectName("hTNLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hTNLabel)
        self.input_hoten = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.input_hoten.setMaximumSize(QtCore.QSize(280, 16777215))
        self.input_hoten.setObjectName("input_hoten")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_hoten)
        self.mSSinhViNLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.mSSinhViNLabel.setObjectName("mSSinhViNLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mSSinhViNLabel)
        self.input_mssv = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.input_mssv.setMaximumSize(QtCore.QSize(280, 16777215))
        self.input_mssv.setObjectName("input_mssv")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_mssv)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(400, 30, 361, 91))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.emailLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.emailLabel_2.setObjectName("emailLabel_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.emailLabel_2)
        self.input_email = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.input_email.setMaximumSize(QtCore.QSize(240, 16777215))
        self.input_email.setObjectName("input_email")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_email)
        self.sINThoILabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.sINThoILabel.setObjectName("sINThoILabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sINThoILabel)
        self.input_sdt = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.input_sdt.setMaximumSize(QtCore.QSize(240, 16777215))
        self.input_sdt.setObjectName("input_sdt")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_sdt)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.bang_danh_sach = QtWidgets.QTableWidget(self.groupBox_2)
        self.bang_danh_sach.setGeometry(QtCore.QRect(50, 20, 711, 621))
        self.bang_danh_sach.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bang_danh_sach.setLineWidth(3)
        self.bang_danh_sach.setObjectName("bang_danh_sach")
        self.bang_danh_sach.setColumnCount(2)
        self.bang_danh_sach.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bang_danh_sach.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bang_danh_sach.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Điều hướng"))
        self.btn_page_dangky.setText(_translate("MainWindow", "Đăng ký mã vạch"))
        self.btn_page_quanly.setText(_translate("MainWindow", "Quản Lý Điểm Danh"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Quản lý điểm danh"))
        self.label_frameBarCode.setText(_translate("MainWindow", "khung hiển thị"))
        self.btn_openCam.setText(_translate("MainWindow", "Mở Camera "))
        self.btn_closeCam.setText(_translate("MainWindow", "Tắt Camera "))
        self.groupBox_4.setTitle(_translate("MainWindow", "Lấy danh sách lớp học"))
        self.label_2.setText(_translate("MainWindow", "Mã học phần"))
        self.emailLabel.setText(_translate("MainWindow", "Nhóm"))
        self.label.setText(_translate("MainWindow", "Tuần học"))
        self.btn_tim_danhSach.setText(_translate("MainWindow", "Lấy danh sách"))
        self.btn_luu_danh_sach.setText(_translate("MainWindow", "Lưu danh sách"))
        self.btn_export_file.setText(_translate("MainWindow", "Xuất file excel"))
        self.btn_clear_input.setText(_translate("MainWindow", "Làm mới"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Thông tin sinh viên"))
        self.hTNLabel.setText(_translate("MainWindow", "Họ tên"))
        self.mSSinhViNLabel.setText(_translate("MainWindow", "MSSV"))
        self.emailLabel_2.setText(_translate("MainWindow", "Email"))
        self.sINThoILabel.setText(_translate("MainWindow", "Số điện thoại"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Danh sách"))
        item = self.bang_danh_sach.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mssv"))
        item = self.bang_danh_sach.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tuần "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
